### ISSUE TITLE
test_Neighbourlist

### ISSUE THREAD

**Issue by BioFreak95** [BioFreak95/Particle_Simulation#12]
There are no tests for neighbour-lists right now. @arjum92 it would be great if you add some

**Comment by arjum92** [comment]
Ok... I will try

**Comment by BioFreak95** [comment]
@Mnlohani I see you wrote some tests, but you have closed the Pull Request before merging. Please open a new Pull Request, so we can merge them into the master branch.

**Comment by BioFreak95** [comment]
Some tests are missing actually. wrote more tests for NL and cell_neighbours. Pay attention to new implemented second layer in cell_neighbours, which check, if a cell is a mirror or a real cell.
Please implement min 2 tests per dimension and function and wrote some defencive tests. What happens at wrong inputs.

**Comment by BioFreak95** [comment]
done
