### ISSUE TITLE
Alternate way for periodic_box_shift function in CellNeighbours.py for avoiding loop

### ISSUE THREAD

**Issue by Mnlohani** [BioFreak95/Particle_Simulation#27]
### Issue Title ###
You can use the following code : x1_periodic same as x
x = np.array([ 1.5,  1., 5.5 ])
x1 = np.array([  13.5,   1. ,   5.5])
box = np.array( [  12 ,  13. ,   14])

**x1_periodic = np.remainder(x1, box)**
print(x1_periodic)

#same point which is 1-2 box away is giving correct point
x5 = np.array([  25.5,   1. ,   5.5])
x5_periodic = np.remainder(x5, box)
print(x5_periodic)

#same point on left hand side periodic is giving correct point:
x6 = np.array([  -10.5,   1. ,   5.5])
x6_periodic = np.remainder(x6, box)
print(x6_periodic)

**Comment by BioFreak95** [comment]
That is interesting. I will check this.

**Comment by BioFreak95** [comment]
That is not necessary.
We wrote an shift function. The point is, that np.remainder have a better performance, because of vectorisation. But we use Jit. So np.remainder wouldn´t help us significant ant the performance of our function with jit is similar to np.remainder.
