### ISSUE TITLE
 lennard jones calculate distance

### ISSUE THREAD

**Issue by Mnlohani** [BioFreak95/Particle_Simulation#38]
### Issue Title ###
Pbc distance 
### Expected Behavior ###
periodic distance
### Actual Behavior ###
regular distance

**Comment by BioFreak95** [comment]
In the calculate_distance function at LJ, its not necessary to pay attention to PBC. This function only calculate distance between two particles. Mathematicaly, the function calculate the euclidean distance. Not more.
