### ISSUE TITLE
Toolbox - data_import

### ISSUE THREAD

**Issue by BioFreak95** [BioFreak95/Particle_Simulation#44]
### Issue Title ###
Toolbox - data_import
### Expected Behavior ###
implement an function, which import particle data and parameter
### Actual Behavior ###
/
#### Additional Part for Developers #
/
##### Steps for reproducing the expected behavior
/

**Comment by hkneiding** [comment]
@Mnlohani pls do that

**Comment by hkneiding** [comment]
this has been done and can be closed
