### ISSUE TITLE
Metropolis tests

### ISSUE THREAD

**Issue by BioFreak95** [BioFreak95/Particle_Simulation#47]
### Issue Title ###
Metropolis tests
### Expected Behavior ###
min 2 tests for each metropolis function
defencive tests, for wrong inputs
### Actual Behavior ###
/
#### Additional Part for Developers #
/
##### Steps for reproducing the expected behavior
/

**Comment by Mnlohani** [comment]
added few test cases , but for the functions which are returning objects, which type of test cases should be added? And object is not being printed . I think __repr__ function should be added for objects printing. Also raising  few issues regarding Metropolis test cases . please validate them.

**Comment by BioFreak95** [comment]
fixed
