### ISSUE TITLE
for loop lines in System.py

### ISSUE THREAD

**Issue by Mnlohani** [BioFreak95/Particle_Simulation#8]
@BioFreak95 Can we use following lines outside of for loop? 
self.totalcellnumber = int(np.prod(self.cellnumber))
self.head = np.zeros(self.totalcellnumber) - 1
self.list = np.zeros(self.particlenumber) - 1
self.mc = np.zeros(3)

**Comment by BioFreak95** [comment]
Yes you are right. This is inefficient. I fixed this.
